### ISSUE TITLE
A character is missing.

### ISSUE THREAD

**Issue by s-hong-s** [mkuznets/latex-illustrator#1]
A character is missing. For example, when entering $S_s T_t$, only 'S T_t' is printed.

To fix this, I think the length value needs to be modified as follows.

Line 66 of [https://github.com/mkuznets/latex-illustrator/blob/master/LaTeX.js#L66](url)
`for( var i=grp.pageItems[0].pageItems.length-1; --i>=0; )`
-->
`for( var i=grp.pageItems[0].pageItems.length; --i>=0; )`

**Comment by mkuznets** [comment]
Sorry for my late reply. It has been long since I used Windows for LaTeX and Illustrator so it took me some time to set up the environment :)

The loop was indeed incorrect, thank you for pointing that out. Characters kept missing though because of the next statement: `grp.pageItems[1].remove();` I've changed it to delete the last item instead which *looks* like a useless frame around a formula.

Now it leaves formulas intact as far as I can see. Could you please test if it works for you?

**Comment by s-hong-s** [comment]
I am sorry for the late reply. I tested the new version you updated with some scripts such as $s_S$ and $\vdots$ which are not displayed correctly under the previous version.

It seems that the new version works well. Thanks for your hard work and maintaining this script. 👍 👍 👍
